### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by steipete** [DHowett/pincrush#1]
Hi Dustin,

thanks for the great library! What license it it under? Can you make it MIT?
the code may imply that it's public domain, but I don't like ambiguity.

Thanks!
Peter

**Comment by steipete** [comment]
5 years later, no response. Guess I'll close this.

**Comment by DHowett** [comment]
@steipete Time really does fly. Sorry I let this issue sit, stale and rot for five years. I really dropped the ball. ☹️

**Comment by steipete** [comment]
Oh wow - thanks a bunch! 💙
